### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by Enkuushka** [etodanik/angular-schema-form-file#1]
can you show some usage example?

**Comment by Enkuushka** [comment]
Answering to myself :p

include all the files and don't forget to load ng-file-upload plugin. If you can't find the version see in the required packages specified in bower.js file of this project.

### Schema

```
{
   "type":"object",
   "properties":{
            "myfilefield":{
                   "type":"object",
                   "format":"file",
                   "title":"Image",
                   "x-schema-form":{
                           "type":"file"
                   }
             }
      }
}
```

**Comment by melothegoodfellow** [comment]
@Enkuushka I actually wanted some help in installing this add-on.
How can i use it along with Angular Schema Form?

**Comment by Enkuushka** [comment]
@melz007 read the entry above. What is the problem that you are facing?

**Comment by melothegoodfellow** [comment]
**Edit:**
I have done everything what you have mentioned above but issue i am facing is basically i am not getting or i am missing something for the **assureitDecoratorUpload** directive for file upload. have you done file upload using this directive?

**Comment by melothegoodfellow** [comment]
@Enkuushka I got it to work. Thanks for your above comment.
